#!/usr/bin/env node

const ipfsAPI = require('ipfs-api')

const DIR = './decompressed'
const ipfs = ipfsAPI(
  process.env.IPFS_HOST || 'localhost',
  process.env.IPFS_PORT || 5001,
  { protocol: process.env.IPFS_PROTOCOL || 'http' }
)

ipfs.util.addFromFs(DIR, { recursive: true }, (err, result) => {
  if (err) throw err

  // last returned hash is the root hash
  const object = result[result.length - 1]

  console.log('pinning', object)

  ipfs.pin.add(object.hash, { recursive: true }, (err) => {
    if (err) throw err
    console.log('pinned', object.hash)
  })
})
